// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {capability} from '../models';
import {api} from '../models';
import {permissions} from '../models';
import {plugin} from '../models';

export function ArchiveWorkspaceNode(arg1:string):Promise<string>;

export function CloseVault():Promise<void>;

export function CreateVault(arg1:string):Promise<void>;

export function CreateWorkspaceNode(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function DisablePlugin(arg1:string):Promise<string>;

export function EnablePlugin(arg1:string):Promise<string>;

export function GetAppSettings():Promise<Record<string, any>>;

export function GetCapabilities():Promise<Array<capability.Entry>>;

export function GetContributions():Promise<api.ContributionSummary>;

export function GetCurrentWorkspaceNode():Promise<Record<string, any>>;

export function GetPermissions():Promise<Array<permissions.Entry>>;

export function GetPlugins():Promise<Array<plugin.Plugin>>;

export function GetVaultPluginState():Promise<Record<string, any>>;

export function GetVaultStatus():Promise<Record<string, string>>;

export function GetWorkspaceTree():Promise<Record<string, any>>;

export function MoveWorkspaceNode(arg1:string,arg2:string):Promise<string>;

export function OpenVault(arg1:string):Promise<void>;

export function ReadPluginDataJSON(arg1:string,arg2:string):Promise<Record<string, any>>;

export function ReadPluginSetting(arg1:string,arg2:string):Promise<any>;

export function ReadPluginSettings(arg1:string):Promise<Record<string, any>>;

export function RecordDesiredPlugin(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ReloadPlugins():Promise<number|string>;

export function RenameWorkspaceNode(arg1:string,arg2:string):Promise<string>;

export function SelectDirectory():Promise<string>;

export function SelectVaultForOpen():Promise<string>;

export function SetCurrentVault(arg1:string):Promise<string>;

export function SetCurrentWorkspaceNode(arg1:string):Promise<string>;

export function UpdateAppSettings(arg1:Record<string, any>):Promise<string>;

export function WritePluginDataJSON(arg1:string,arg2:string,arg3:Record<string, any>):Promise<string>;

export function WritePluginSetting(arg1:string,arg2:string,arg3:any):Promise<string>;

export function WritePluginSettings(arg1:string,arg2:Record<string, any>):Promise<string>;
