// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {capability} from '../models';
import {api} from '../models';
import {permissions} from '../models';
import {plugin} from '../models';

export function GetCapabilities():Promise<Array<capability.Entry>>;

export function GetContributions():Promise<api.ContributionSummary>;

export function GetPermissions():Promise<Array<permissions.Entry>>;

export function GetPlugins():Promise<Array<plugin.Plugin>>;

export function ReloadPlugins():Promise<number|string>;

export function Startup():Promise<void>;
