// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {workspace} from '../models';
import {context} from '../models';
import {workbench} from '../models';
import {capability} from '../models';
import {api} from '../models';
import {permissions} from '../models';
import {plugin} from '../models';
import {files} from '../models';
import {workspacetree} from '../models';
import {notifications} from '../models';

export function ArchiveWorkspaceNode(arg1:string):Promise<string>;

export function ClearPluginNotifications(arg1:string):Promise<string>;

export function CloseVault():Promise<void>;

export function CreateFolderV2(arg1:string,arg2:string):Promise<Record<string, any>>;

export function CreateVault(arg1:string):Promise<void>;

export function CreateVaultFolder(arg1:string,arg2:string):Promise<string>;

export function CreateWorkspace(arg1:string,arg2:string):Promise<workspace.Workspace|string>;

export function CreateWorkspaceNode(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function CreateWorkspaceV2(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function DeleteVaultTrash(arg1:string,arg2:string):Promise<string>;

export function DisablePlugin(arg1:string):Promise<string>;

export function DomReady(arg1:context.Context):Promise<void>;

export function EditWorkbenchResource(arg1:string,arg2:Record<string, any>):Promise<workbench.OpenResourceResult|string>;

export function EnablePlugin(arg1:string):Promise<string>;

export function ExecutePluginCommand(arg1:string,arg2:string,arg3:Record<string, any>):Promise<Record<string, any>|string>;

export function GetAppSettings():Promise<Record<string, any>>;

export function GetCapabilities():Promise<Array<capability.Entry>>;

export function GetContributions():Promise<api.ContributionSummary>;

export function GetCurrentWorkspace():Promise<Record<string, any>>;

export function GetCurrentWorkspaceNode():Promise<Record<string, any>>;

export function GetFolderAppearance(arg1:string):Promise<Record<string, any>>;

export function GetFolderByID(arg1:string):Promise<Record<string, any>>;

export function GetPermissions():Promise<Array<permissions.Entry>>;

export function GetPluginAssetContent(arg1:string,arg2:string):Promise<string|string>;

export function GetPluginCapability(arg1:string,arg2:string):Promise<Record<string, any>|string>;

export function GetPluginFrontendInfo(arg1:string):Promise<Record<string, any>>;

export function GetPluginLocalization(arg1:string,arg2:string):Promise<Record<string, string>|string>;

export function GetPlugins():Promise<Array<plugin.Plugin>>;

export function GetVaultFileMetadata(arg1:string,arg2:string):Promise<files.FileMetadata|string>;

export function GetVaultPluginState():Promise<Record<string, any>>;

export function GetVaultStatus():Promise<Record<string, string>>;

export function GetWorkbenchOpenedResources():Promise<Array<workbench.OpenedResource>>;

export function GetWorkbenchPreferences():Promise<workbench.Preferences>;

export function GetWorkspaceByID(arg1:string):Promise<Record<string, any>>;

export function GetWorkspaceMetadata(arg1:string):Promise<workspace.Metadata|string>;

export function GetWorkspaceTree():Promise<Record<string, any>>;

export function GetWorkspaceTreeDiagnostics():Promise<Array<workspacetree.TreeDiagnostic>>;

export function GetWorkspaceTreeV2():Promise<Record<string, any>>;

export function ListPluginCapabilities(arg1:string):Promise<Array<capability.Entry>|string>;

export function ListVaultFiles(arg1:string,arg2:string):Promise<Array<files.FileEntry>|string>;

export function ListVaultTrash(arg1:string):Promise<Array<files.TrashEntry>|string>;

export function ListWorkspaceIdentities():Promise<Array<workspace.WorkspaceIdentity>|string>;

export function ListWorkspaceTemplates():Promise<Array<workspace.WorkspaceTemplate>|string>;

export function ListWorkspaces():Promise<Array<workspace.Workspace>|string>;

export function MoveFolderV2(arg1:string,arg2:string):Promise<string>;

export function MoveVaultPath(arg1:string,arg2:string,arg3:string,arg4:files.MoveOptions):Promise<string>;

export function MoveWorkspaceNode(arg1:string,arg2:string):Promise<string>;

export function MoveWorkspaceV2(arg1:string,arg2:string):Promise<string>;

export function OpenExternalURL(arg1:string,arg2:string):Promise<string>;

export function OpenVault(arg1:string):Promise<void>;

export function OpenVaultPathExternal(arg1:string,arg2:string):Promise<string>;

export function OpenWorkbenchResource(arg1:string,arg2:Record<string, any>):Promise<workbench.OpenResourceResult|string>;

export function PluginBrowserReceiverPairing(arg1:string):Promise<Record<string, string>|string>;

export function PluginRotateBrowserReceiverToken(arg1:string):Promise<Record<string, string>|string>;

export function PluginSecretsCopyLink(arg1:string,arg2:string):Promise<string|string>;

export function PluginSecretsDelete(arg1:string,arg2:string):Promise<string>;

export function PluginSecretsList(arg1:string):Promise<Array<Record<string, any>>|string>;

export function PluginSecretsRead(arg1:string,arg2:string):Promise<Record<string, any>|string>;

export function PluginSecretsStatus(arg1:string):Promise<Record<string, any>|string>;

export function PluginSecretsUnlock(arg1:string,arg2:string):Promise<string>;

export function PluginSecretsWrite(arg1:string,arg2:Record<string, any>):Promise<Record<string, any>|string>;

export function PluginSyncConfigure(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function PluginSyncDisconnect(arg1:string):Promise<string>;

export function PluginSyncNow(arg1:string):Promise<Record<string, any>|string>;

export function PluginSyncResetKey(arg1:string):Promise<string>;

export function PluginSyncSetInterval(arg1:string,arg2:number):Promise<string>;

export function PluginSyncStatus(arg1:string):Promise<api.SyncStatusDTO|string>;

export function PluginSyncTestConnection(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function PublishPluginEvent(arg1:string,arg2:string,arg3:Record<string, any>):Promise<string>;

export function PurgeWorkspaceTrash(arg1:string):Promise<string>;

export function Quit():Promise<void>;

export function ReadPluginDataJSON(arg1:string,arg2:string):Promise<Record<string, any>>;

export function ReadPluginDataNDJSON(arg1:string,arg2:string):Promise<Array<Record<string, any>>>;

export function ReadPluginSetting(arg1:string,arg2:string):Promise<any>;

export function ReadPluginSettings(arg1:string):Promise<Record<string, any>|string>;

export function ReadVaultFileBytes(arg1:string,arg2:string):Promise<files.FileBytes|string>;

export function ReadVaultTextFile(arg1:string,arg2:string):Promise<string|string>;

export function RecordDesiredPlugin(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ReloadPlugins():Promise<number|string>;

export function RenameFolderV2(arg1:string,arg2:string):Promise<string>;

export function RenameWorkspace(arg1:string,arg2:string):Promise<string>;

export function RenameWorkspaceNode(arg1:string,arg2:string):Promise<string>;

export function RenameWorkspaceV2(arg1:string,arg2:string):Promise<string>;

export function RepairWorkspaceIdentity(arg1:string,arg2:string):Promise<string>;

export function ReplacePluginNotifications(arg1:string,arg2:Array<notifications.Request>):Promise<string>;

export function RescanWorkspaceTree():Promise<string>;

export function ResetFolderAppearance(arg1:string):Promise<string>;

export function RestoreVaultTrash(arg1:string,arg2:string,arg3:files.RestoreOptions):Promise<string|string>;

export function RestoreWorkspaceTrash(arg1:string,arg2:string):Promise<workspace.Workspace|string>;

export function SelectDirectory():Promise<string>;

export function SelectVaultForOpen():Promise<string>;

export function SetCurrentVault(arg1:string):Promise<string>;

export function SetCurrentWorkspace(arg1:string):Promise<string>;

export function SetCurrentWorkspaceNode(arg1:string):Promise<string>;

export function SetCurrentWorkspaceV2(arg1:string):Promise<string>;

export function SetFolderAppearance(arg1:string,arg2:Record<string, any>):Promise<string>;

export function SetNotificationService(arg1:api.notificationService):Promise<void>;

export function SetTrayReady(arg1:boolean):Promise<void>;

export function ShowVaultPathInFolder(arg1:string,arg2:string):Promise<string>;

export function ShowWindow():Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function SubscribePluginEvent(arg1:string,arg2:string):Promise<string>;

export function TrashFolderV2(arg1:string):Promise<Record<string, any>>;

export function TrashVaultPath(arg1:string,arg2:string):Promise<files.TrashResult|string>;

export function TrashWorkspace(arg1:string):Promise<workspace.TrashResult|string>;

export function TrashWorkspaceV2(arg1:string):Promise<Record<string, any>>;

export function UpdateAppSettings(arg1:Record<string, any>):Promise<string>;

export function UpdateWorkbenchPreferences(arg1:workbench.Preferences):Promise<string>;

export function UpdateWorkspaceMetadata(arg1:string,arg2:workspace.MetadataPatch):Promise<workspace.Metadata|string>;

export function WriteFrontendLog(arg1:string,arg2:string):Promise<void>;

export function WritePluginDataJSON(arg1:string,arg2:string,arg3:Record<string, any>):Promise<string>;

export function WritePluginDataNDJSON(arg1:string,arg2:string,arg3:Array<Record<string, any>>):Promise<string>;

export function WritePluginSetting(arg1:string,arg2:string,arg3:any):Promise<string>;

export function WritePluginSettings(arg1:string,arg2:Record<string, any>):Promise<string>;

export function WriteVaultFileBytes(arg1:string,arg2:string,arg3:string,arg4:files.WriteOptions):Promise<string>;

export function WriteVaultTextFile(arg1:string,arg2:string,arg3:string,arg4:files.WriteOptions):Promise<string>;
