// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseVault() {
  return window['go']['api']['App']['CloseVault']();
}

export function CreateVault(arg1) {
  return window['go']['api']['App']['CreateVault'](arg1);
}

export function DisablePlugin(arg1) {
  return window['go']['api']['App']['DisablePlugin'](arg1);
}

export function EnablePlugin(arg1) {
  return window['go']['api']['App']['EnablePlugin'](arg1);
}

export function GetAppSettings() {
  return window['go']['api']['App']['GetAppSettings']();
}

export function GetCapabilities() {
  return window['go']['api']['App']['GetCapabilities']();
}

export function GetContributions() {
  return window['go']['api']['App']['GetContributions']();
}

export function GetPermissions() {
  return window['go']['api']['App']['GetPermissions']();
}

export function GetPlugins() {
  return window['go']['api']['App']['GetPlugins']();
}

export function GetVaultPluginState() {
  return window['go']['api']['App']['GetVaultPluginState']();
}

export function GetVaultStatus() {
  return window['go']['api']['App']['GetVaultStatus']();
}

export function OpenVault(arg1) {
  return window['go']['api']['App']['OpenVault'](arg1);
}

export function ReadPluginDataJSON(arg1, arg2) {
  return window['go']['api']['App']['ReadPluginDataJSON'](arg1, arg2);
}

export function ReadPluginSetting(arg1, arg2) {
  return window['go']['api']['App']['ReadPluginSetting'](arg1, arg2);
}

export function ReadPluginSettings(arg1) {
  return window['go']['api']['App']['ReadPluginSettings'](arg1);
}

export function RecordDesiredPlugin(arg1, arg2, arg3) {
  return window['go']['api']['App']['RecordDesiredPlugin'](arg1, arg2, arg3);
}

export function ReloadPlugins() {
  return window['go']['api']['App']['ReloadPlugins']();
}

export function SelectDirectory() {
  return window['go']['api']['App']['SelectDirectory']();
}

export function SelectVaultForOpen() {
  return window['go']['api']['App']['SelectVaultForOpen']();
}

export function SetCurrentVault(arg1) {
  return window['go']['api']['App']['SetCurrentVault'](arg1);
}

export function UpdateAppSettings(arg1) {
  return window['go']['api']['App']['UpdateAppSettings'](arg1);
}

export function WritePluginDataJSON(arg1, arg2, arg3) {
  return window['go']['api']['App']['WritePluginDataJSON'](arg1, arg2, arg3);
}

export function WritePluginSetting(arg1, arg2, arg3) {
  return window['go']['api']['App']['WritePluginSetting'](arg1, arg2, arg3);
}

export function WritePluginSettings(arg1, arg2) {
  return window['go']['api']['App']['WritePluginSettings'](arg1, arg2);
}
