// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseVault() {
  return window['go']['api']['App']['CloseVault']();
}

export function CreateVault(arg1) {
  return window['go']['api']['App']['CreateVault'](arg1);
}

export function GetCapabilities() {
  return window['go']['api']['App']['GetCapabilities']();
}

export function GetContributions() {
  return window['go']['api']['App']['GetContributions']();
}

export function GetPermissions() {
  return window['go']['api']['App']['GetPermissions']();
}

export function GetPlugins() {
  return window['go']['api']['App']['GetPlugins']();
}

export function GetVaultStatus() {
  return window['go']['api']['App']['GetVaultStatus']();
}

export function OpenVault(arg1) {
  return window['go']['api']['App']['OpenVault'](arg1);
}

export function ReloadPlugins() {
  return window['go']['api']['App']['ReloadPlugins']();
}

export function Startup() {
  return window['go']['api']['App']['Startup']();
}
