// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ArchiveWorkspaceNode(arg1) {
  return window['go']['api']['App']['ArchiveWorkspaceNode'](arg1);
}

export function CloseVault() {
  return window['go']['api']['App']['CloseVault']();
}

export function CreateNote(arg1, arg2) {
  return window['go']['api']['App']['CreateNote'](arg1, arg2);
}

export function CreateVault(arg1) {
  return window['go']['api']['App']['CreateVault'](arg1);
}

export function CreateVaultFolder(arg1, arg2) {
  return window['go']['api']['App']['CreateVaultFolder'](arg1, arg2);
}

export function CreateWorkspace(arg1, arg2) {
  return window['go']['api']['App']['CreateWorkspace'](arg1, arg2);
}

export function CreateWorkspaceNode(arg1, arg2, arg3) {
  return window['go']['api']['App']['CreateWorkspaceNode'](arg1, arg2, arg3);
}

export function DisablePlugin(arg1) {
  return window['go']['api']['App']['DisablePlugin'](arg1);
}

export function EditWorkbenchResource(arg1, arg2) {
  return window['go']['api']['App']['EditWorkbenchResource'](arg1, arg2);
}

export function EnablePlugin(arg1) {
  return window['go']['api']['App']['EnablePlugin'](arg1);
}

export function EnsureOverview(arg1) {
  return window['go']['api']['App']['EnsureOverview'](arg1);
}

export function ExecutePluginCommand(arg1, arg2, arg3) {
  return window['go']['api']['App']['ExecutePluginCommand'](arg1, arg2, arg3);
}

export function GetAppSettings() {
  return window['go']['api']['App']['GetAppSettings']();
}

export function GetCapabilities() {
  return window['go']['api']['App']['GetCapabilities']();
}

export function GetContributions() {
  return window['go']['api']['App']['GetContributions']();
}

export function GetCurrentWorkspace() {
  return window['go']['api']['App']['GetCurrentWorkspace']();
}

export function GetCurrentWorkspaceNode() {
  return window['go']['api']['App']['GetCurrentWorkspaceNode']();
}

export function GetPermissions() {
  return window['go']['api']['App']['GetPermissions']();
}

export function GetPluginAssetContent(arg1, arg2) {
  return window['go']['api']['App']['GetPluginAssetContent'](arg1, arg2);
}

export function GetPluginCapability(arg1, arg2) {
  return window['go']['api']['App']['GetPluginCapability'](arg1, arg2);
}

export function GetPluginFrontendInfo(arg1) {
  return window['go']['api']['App']['GetPluginFrontendInfo'](arg1);
}

export function GetPlugins() {
  return window['go']['api']['App']['GetPlugins']();
}

export function GetVaultFileMetadata(arg1, arg2) {
  return window['go']['api']['App']['GetVaultFileMetadata'](arg1, arg2);
}

export function GetVaultPluginState() {
  return window['go']['api']['App']['GetVaultPluginState']();
}

export function GetVaultStatus() {
  return window['go']['api']['App']['GetVaultStatus']();
}

export function GetWorkbenchOpenedResources() {
  return window['go']['api']['App']['GetWorkbenchOpenedResources']();
}

export function GetWorkbenchPreferences() {
  return window['go']['api']['App']['GetWorkbenchPreferences']();
}

export function GetWorkspaceMetadata(arg1) {
  return window['go']['api']['App']['GetWorkspaceMetadata'](arg1);
}

export function GetWorkspaceTree() {
  return window['go']['api']['App']['GetWorkspaceTree']();
}

export function ListNotes(arg1) {
  return window['go']['api']['App']['ListNotes'](arg1);
}

export function ListPluginCapabilities(arg1) {
  return window['go']['api']['App']['ListPluginCapabilities'](arg1);
}

export function ListVaultFiles(arg1, arg2) {
  return window['go']['api']['App']['ListVaultFiles'](arg1, arg2);
}

export function ListWorkspaces() {
  return window['go']['api']['App']['ListWorkspaces']();
}

export function MoveVaultPath(arg1, arg2, arg3, arg4) {
  return window['go']['api']['App']['MoveVaultPath'](arg1, arg2, arg3, arg4);
}

export function MoveWorkspaceNode(arg1, arg2) {
  return window['go']['api']['App']['MoveWorkspaceNode'](arg1, arg2);
}

export function NormalizeNoteTitle(arg1) {
  return window['go']['api']['App']['NormalizeNoteTitle'](arg1);
}

export function OpenVault(arg1) {
  return window['go']['api']['App']['OpenVault'](arg1);
}

export function OpenWorkbenchResource(arg1, arg2) {
  return window['go']['api']['App']['OpenWorkbenchResource'](arg1, arg2);
}

export function PublishPluginEvent(arg1, arg2, arg3) {
  return window['go']['api']['App']['PublishPluginEvent'](arg1, arg2, arg3);
}

export function ReadNote(arg1) {
  return window['go']['api']['App']['ReadNote'](arg1);
}

export function ReadPluginDataJSON(arg1, arg2) {
  return window['go']['api']['App']['ReadPluginDataJSON'](arg1, arg2);
}

export function ReadPluginSetting(arg1, arg2) {
  return window['go']['api']['App']['ReadPluginSetting'](arg1, arg2);
}

export function ReadPluginSettings(arg1) {
  return window['go']['api']['App']['ReadPluginSettings'](arg1);
}

export function ReadVaultTextFile(arg1, arg2) {
  return window['go']['api']['App']['ReadVaultTextFile'](arg1, arg2);
}

export function RecordDesiredPlugin(arg1, arg2, arg3) {
  return window['go']['api']['App']['RecordDesiredPlugin'](arg1, arg2, arg3);
}

export function ReloadPlugins() {
  return window['go']['api']['App']['ReloadPlugins']();
}

export function RenameNote(arg1, arg2) {
  return window['go']['api']['App']['RenameNote'](arg1, arg2);
}

export function RenameWorkspace(arg1, arg2) {
  return window['go']['api']['App']['RenameWorkspace'](arg1, arg2);
}

export function RenameWorkspaceNode(arg1, arg2) {
  return window['go']['api']['App']['RenameWorkspaceNode'](arg1, arg2);
}

export function ResetSyncKey() {
  return window['go']['api']['App']['ResetSyncKey']();
}

export function SaveNote(arg1, arg2) {
  return window['go']['api']['App']['SaveNote'](arg1, arg2);
}

export function SearchNotes(arg1) {
  return window['go']['api']['App']['SearchNotes'](arg1);
}

export function SelectDirectory() {
  return window['go']['api']['App']['SelectDirectory']();
}

export function SelectVaultForOpen() {
  return window['go']['api']['App']['SelectVaultForOpen']();
}

export function SetCurrentVault(arg1) {
  return window['go']['api']['App']['SetCurrentVault'](arg1);
}

export function SetCurrentWorkspace(arg1) {
  return window['go']['api']['App']['SetCurrentWorkspace'](arg1);
}

export function SetCurrentWorkspaceNode(arg1) {
  return window['go']['api']['App']['SetCurrentWorkspaceNode'](arg1);
}

export function SubscribePluginEvent(arg1, arg2) {
  return window['go']['api']['App']['SubscribePluginEvent'](arg1, arg2);
}

export function SyncConfigure(arg1, arg2, arg3) {
  return window['go']['api']['App']['SyncConfigure'](arg1, arg2, arg3);
}

export function SyncDisconnect() {
  return window['go']['api']['App']['SyncDisconnect']();
}

export function SyncNow() {
  return window['go']['api']['App']['SyncNow']();
}

export function SyncSetInterval(arg1) {
  return window['go']['api']['App']['SyncSetInterval'](arg1);
}

export function SyncStatus() {
  return window['go']['api']['App']['SyncStatus']();
}

export function SyncTestConnection(arg1, arg2, arg3) {
  return window['go']['api']['App']['SyncTestConnection'](arg1, arg2, arg3);
}

export function TrashVaultPath(arg1, arg2) {
  return window['go']['api']['App']['TrashVaultPath'](arg1, arg2);
}

export function TrashWorkspace(arg1) {
  return window['go']['api']['App']['TrashWorkspace'](arg1);
}

export function UpdateAppSettings(arg1) {
  return window['go']['api']['App']['UpdateAppSettings'](arg1);
}

export function UpdateWorkbenchPreferences(arg1) {
  return window['go']['api']['App']['UpdateWorkbenchPreferences'](arg1);
}

export function UpdateWorkspaceMetadata(arg1, arg2) {
  return window['go']['api']['App']['UpdateWorkspaceMetadata'](arg1, arg2);
}

export function WriteFrontendLog(arg1, arg2) {
  return window['go']['api']['App']['WriteFrontendLog'](arg1, arg2);
}

export function WritePluginDataJSON(arg1, arg2, arg3) {
  return window['go']['api']['App']['WritePluginDataJSON'](arg1, arg2, arg3);
}

export function WritePluginSetting(arg1, arg2, arg3) {
  return window['go']['api']['App']['WritePluginSetting'](arg1, arg2, arg3);
}

export function WritePluginSettings(arg1, arg2) {
  return window['go']['api']['App']['WritePluginSettings'](arg1, arg2);
}

export function WriteVaultTextFile(arg1, arg2, arg3, arg4) {
  return window['go']['api']['App']['WriteVaultTextFile'](arg1, arg2, arg3, arg4);
}
